name: Disable Checking ServerName

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches: [ main ]
  # pull_request_target:
  #   types: [assigned, opened, synchronize, reopened]
  repository_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: modify
        run: |
          cd tailscale
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go

      - name: Read VERSION.txt from submodule
        id: get_version
        run: |
          VERSION_FILE="tailscale/VERSION.txt"
          VERSION="v$(cat "$VERSION_FILE" | tr -d '[:space:]' | tr -d '\r\n')"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a single command using the runners shell
      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v5
        with:
          file: 'Dockerfile'
          platforms: linux/amd64,linux/arm64,linux/arm
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ip_derper:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/ip_derper:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: false